import { IconBase } from "react-icons/lib";

export const metadata = {
  title: "Next.js",
  IconBase,
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
